### ISSUE TITLE
Power pin positioning

### ISSUE THREAD

**Issue by fruchti** [horizon-eda/horizon-pool-convention#7]
Sorry that it has taken me so long to open this issue. Now, it's finally here for you all to discuss!

There should be a rule where power pins have to be placed in symbols. KiCad [says](http://kicad-pcb.org/libraries/klc/S4.2/) that they must be on the top and bottom of a symbol. I already had started [a discussion](https://github.com/carrotIndustries/horizon-pool/pull/11) with @carrotIndustries about this question before I started this convention attempt.

In my opinion, the “always on top/bottom” rule isn't optimal, but finding a concise alternative isn't easy. In the issue linked above I proposed some, which I want to summarise along with some subjective pros and cons.

- Positive on top, negative on bottom (the KiCad way)
  - Pro:
    - People are used to this convention.
    - Good usability for analogue ICs.
  - Con:
    - Symbols are unnecessarily large, because pin names get in each other's ways (I don't like the aesthetics of this one).
    - Placing bypass caps on the supply rails is awkward.
- Use the alignment taking up the least space in the schematic, including external components used in most cases (e. g. for microcontrollers: bypass capacitors, crystal, etc.)
  - Pro:
    - Tidy and space-saving schematics guaranteed.
  - Con:
    - Not that objective and hard to check.
- Separate power unit for all cases except where the power pins have more like an analogue function (e. g. voltage regulators)
  - Pro:
    - Having the power supply separate from the signal flow/main logic can boost readability.
    - Having a power schematic sheet gets straightforward and natural.
    - Supplying different voltage levels to an IC is easier. Putting a filter between VDD and VDDA of a chip is cleaner than ever.
  - Con:
    - Favours schematic fragmentation and might hinder readability.
    - More error prone: It's more likely to forget a power component than to miss an unconnected pin already on the schematic (although the ERC should check for this?).

I'd like to hear some more possibilities from you where the power pins could be and how we can boil that down into a rule.

**Comment by carrotIndustries** [comment]
https://github.com/carrotIndustries/horizon/commit/7c432b2b54b5d5af3461d63126da494c4da0bfeb adds support for horizontal text on vertical pins

**Comment by fruchti** [comment]
TBH, I'm still a fan of keeping the top and bottom of a (rectangular) symbol pin-free. It plays along nicely with most schematics' signal flow from left to right and doesn't take too much additional space. Some examples from KiCAD:
![2018-12-02-153450_2476x1488_scrot](https://user-images.githubusercontent.com/11243448/49341070-9f91a280-f648-11e8-9f60-6a3d2b713e5b.png)
![2018-12-02-153127_1211x1496_scrot](https://user-images.githubusercontent.com/11243448/49341071-a3252980-f648-11e8-8441-6ab0d443e21e.png)

But aesthetics are a matter of opinion, of course. With the perpendicular pin names of c345cf4fb5b7c380b64327ce597b0a2eba622223 a lot of the pain points for me of power pins on the top and bottom are addressed. If we want these pins on the top and bottom, I'd wager for having the same name orientation for all pins.

**Comment by fruchti** [comment]
As mentioned [here](https://github.com/carrotIndustries/horizon-pool/pull/70#issuecomment-443514434), power pins on the top and bottom could look something like this:
![2018-12-22-191326_1600x900_scrot](https://user-images.githubusercontent.com/11243448/50377469-1bff1c00-061e-11e9-8df3-8de79efc59cf.png)
If you want to play around, you can check out this symbol [via its PR](https://github.com/carrotIndustries/horizon-pool/pull/76).

**Comment by fruchti** [comment]
@carrotIndustries, @atoav: Any comments on this?

**Comment by fruchti** [comment]
With the recent input from @carrotIndustries in https://github.com/horizon-eda/horizon-pool/pull/11#issuecomment-759699745 I’d consider this issue resolved for now. As always, I’m happy to re-open it if anyone has additional comments!
